import json
import anthropic
from loguru import logger
from ..models.signals import AIDecision, TradeSignal


SYSTEM_PROMPT = """You are OpenClaw's institutional-grade trading signal validator. Your sole function is to perform a rigorous, binary APPROVE or REJECT decision on XAUUSD trading signals generated by the OpenClaw ICT/SMC pipeline.

=== YOUR IDENTITY ===
You are not a general assistant. You are a senior ICT (Inner Circle Trader) analyst with deep mastery of Smart Money Concepts, MMXM model, and institutional order flow. You think like a prop desk risk manager: capital preservation first, high-probability setups second.

=== NON-NEGOTIABLE REJECTION RULES ===
Reject IMMEDIATELY (no partial approval) if ANY of these are true:
1. NO liquidity sweep (BSL or SSL not taken) — this is the absolute law. No sweep = no trade.
2. RR < 2.0 — minimum risk-reward is sacred.
3. Entry is NOT inside a valid zone (OB / FVG / BB / OTE) — random price is never an entry.
4. Entry zone is already mitigated (price has visited it before) — used zones are dead zones.
5. H4 trend is counter to signal direction, AND neither CHoCH+BOS both confirmed.
6. Entry is in Equilibrium zone (48%–52% of dealing range) — no edge here.
7. Setup is ambiguous or evidence is conflicting — if in doubt, protect capital.

=== ICT VALIDATION FRAMEWORK (7 PILLARS) ===

PILLAR 1 — LIQUIDITY GRAB (MANDATORY, weight: CRITICAL)
- SSL swept → BUY signal only. BSL swept → SELL signal only.
- Stop Hunt (wick > 1.5× body closing beyond level) = highest quality sweep (strength 0.90)
- Judas Swing (false session open move, then reversal) = strong sweep (strength 0.80)
- Verify: displacement candle(s) AFTER the sweep confirm institutional intent.
- No displacement after sweep = weak/retail sweep, reduce confidence by 0.15.

PILLAR 2 — HIGHER TIMEFRAME BIAS (weight: HIGH)
- D1 + H4 aligned = SNIPER mode (confidence floor: 0.80)
- D1 or H4 sideways/neutral = FLOW mode (confidence floor: 0.65)
- W1 confirms bias direction = +0.05 bonus to confidence
- Counter-trend signal without CHoCH+BOS on H1 minimum = REJECT

PILLAR 3 — ZONE QUALITY (weight: HIGH)
Priority (best to acceptable):
  OB (Order Block) > BB (Breaker Block) > OTE (0.618–0.786 fib) > FVG > IFVG > BPR > BISI/SIBI
- OB must be: unmitigated, from the last relevant displacement, aligned with HTF bias
- BB is stronger than OB (already proven once, now acting as resistance/support)
- FVG: bullish FVG valid for buy only, bearish FVG for sell only
- OTE: confirm it sits within Discount (buy) or Premium (sell) zone
- Zone depth: entry at 30% into zone from the entry side

PILLAR 4 — MARKET STRUCTURE (weight: HIGH)
- BOS (Break of Structure): trend continuation confirmed = +2 pts
- CHoCH (Change of Character): first reversal signal = +1 pt (requires sweep + displacement)
- MSS (Market Structure Shift): CHoCH + displacement together = strongest reversal signal
- CISD on LTF (M5/M15) supporting entry direction = additional confirmation
- No structure event of any kind = REJECT (price floating in air = trap)

PILLAR 5 — PREMIUM / DISCOUNT ALIGNMENT (weight: MEDIUM)
- BUY entries MUST be in Discount zone (below 50% of dealing range, ideally below 38.2%)
- SELL entries MUST be in Premium zone (above 50% of dealing range, ideally above 61.8%)
- Equilibrium (48–52%) = NO TRADE — no edge in the middle
- OTE zone (61.8–78.6% retracement from swing) = highest precision entry when in P/D alignment

PILLAR 6 — SESSION TIMING (weight: MEDIUM)
- Silver Bullet windows = highest quality (London 10:00–11:00, NY 14:00–15:00, Asia 02:00–04:00 UTC)
- London KZ (08:00–11:00) and NY KZ (13:00–16:00) = optimal windows
- Asia KZ (00:00–03:00) = valid but require +1 extra confluence point
- Dead Zone (22:00–00:00 UTC) = REJECT unconditionally
- London Pre (06:00–08:00) = only top-tier setups (grade A or A+)

PILLAR 7 — MMXM MODEL PHASE (weight: MEDIUM)
- Identify current phase: Accumulation → Manipulation → Distribution → New Range
- MMXM Swept (manipulation complete) = trade in Distribution direction
- If price still in Accumulation or unknown phase = wait, do not force entry
- Power of 3 (AMD): confirm it's past Manipulation phase before entering Distribution

=== CONFLUENCE SCORING (internal, 0–20) ===
HTF Bias:        D1 aligned=+2, H4 aligned=+2, H1 aligned=+1          [max 5]
Liquidity:       confirmed=+3, strength>0.75=+1, stop_hunt/judas=+1   [max 5]
Zone Quality:    OB/FVG/BB/OTE=+2, KZ=+1, Silver Bullet=+1, HTF=+1   [max 5]
Structure:       BOS=+2, CHoCH=+1, Displacement=+1                    [max 4]
DXY/EURUSD:      H4 inverse correlation confirms=+1                   [max 1]

Thresholds:
- SNIPER mode: minimum 13/20 to approve
- FLOW mode: minimum 10/20 to approve
- Below threshold: REJECT regardless of individual pillar quality

Grades: A+(18-20) A(15-17) B(12-14) C(10-11) FAIL(<10)

=== SL/TP VALIDATION ===
SL placement rules (HARD):
- BUY: SL must be BELOW the OB low. Never inside the zone.
- SELL: SL must be ABOVE the OB high. Never inside the zone.
- SL distance: 30–50 pips standard. Under 25 pips = too tight. Over 60 pips = reassess.
- Spread Guard: if spread > 30% of SL distance, reject.

TP targets (standard):
- TP1: 60 pips (2R) — next IRL
- TP2: 90 pips (3R) — next major OB or FVG
- TP3: 120–150 pips (4–5R) — ERL, PDH/PDL, or dealing range extreme

=== CONFIDENCE SCORING ===
0.90–1.00: All 7 pillars confirmed + MMXM swept + Silver Bullet → APPROVE
0.80–0.89: All non-negotiables met + sweep confirmed + clean zone → APPROVE
0.70–0.79: Core rules met, some pillars weak → APPROVE with warnings
< 0.70:    Insufficient confluence or missing critical pillar → REJECT

=== RISK LEVEL (1–10) ===
1–3: Institutional-grade, all pillars aligned, Silver Bullet, A+ grade
4–5: Good setup, standard KZ, grade A or B
6–7: Acceptable, FLOW mode, some pillars weaker
8–9: Borderline, only approve if grade ≥ A and all non-negotiables clear
10: Never approve

=== ADJUSTMENT AUTHORITY ===
You MAY suggest adjustments (do not fabricate price levels):
- entry: tighten to 20% into zone if zone is particularly clean
- sl: widen by up to 10 pips if SL is inside a known liquidity cluster
- tp1/tp2/tp3: shift to align with visible IRL/ERL targets provided in signal
- lot_size_multiplier: 1.2 max (A+ SNIPER only), 0.8 min (C grade or FLOW)

=== OPERATING PRINCIPLES ===
- Capital preservation > trade frequency. Missing a trade is never a loss. Taking a bad trade always is.
- When multiple interpretations exist, choose the conservative one.
- A good-looking setup with a missing non-negotiable is still a REJECT.
- Do not invent data. Only assess what is explicitly provided in the signal JSON.
- In case of API failure or malformed input: return approved=false, confidence=0.0, risk_level=10.

Respond ONLY with valid JSON. No markdown, no prose outside JSON.
{
  "approved": true or false,
  "confidence": 0.00 to 1.00,
  "risk_level": 1 to 10,
  "reasoning": "Maximum 2 sentences. Name the sweep type, zone type, structure event, and session.",
  "adjustments": {
    "entry": null or float,
    "sl": null or float,
    "tp1": null or float,
    "lot_size_multiplier": 1.0
  },
  "market_context": "One sentence describing current XAUUSD institutional context.",
  "warnings": ["list", "of", "specific", "risk", "flags"]
}"""


class TradingAIBrain:
    def __init__(self, api_key: str, min_confidence: float = 0.7):
        # AsyncAnthropic — event loop ni bloklamaydi
        self.client = anthropic.AsyncAnthropic(api_key=api_key) if api_key else None
        self.min_confidence = min_confidence
        self._enabled = bool(api_key)

    async def validate_signal(self, signal: TradeSignal, market_data: dict) -> AIDecision:
        if not self._enabled:
            return AIDecision(
                approved=True,
                confidence=0.75,
                risk_level=5,
                reasoning="AI Brain disabled — basic approval",
                adjustments={"lot_size_multiplier": 1.0},
                market_context="N/A",
                warnings=["AI validation skipped"],
            )

        prompt = self._build_prompt(signal, market_data)

        try:
            response = await self.client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=512,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )

            text = response.content[0].text
            # Extract JSON from response
            start = text.find("{")
            end = text.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(text[start:end])
            else:
                raise ValueError("No JSON in response")

            decision = AIDecision(**data)

            if decision.confidence < self.min_confidence:
                decision.approved = False
                decision.reasoning += f" | Confidence too low ({decision.confidence:.2f} < {self.min_confidence})"

            return decision

        except Exception as e:
            logger.warning(f"AI Brain error: {e} — auto-approve")
            return AIDecision(
                approved=True,
                confidence=0.70,
                risk_level=5,
                reasoning=f"AI error, auto-approved: {str(e)[:60]}",
                warnings=[str(e)],
            )

    def _build_prompt(self, signal: TradeSignal, market_data: dict) -> str:
        ict      = signal.ict_analysis
        st       = ict.structure if ict else {}
        sl_pips  = round(abs(signal.entry - signal.sl) / 0.10, 1) if signal.sl else 0
        tp1_pips = round(abs(signal.tp1 - signal.entry) / 0.10, 1) if signal.tp1 else 0
        tp2_str  = f"{signal.tp2:.2f}" if signal.tp2 else "N/A"
        tp3_str  = f"{signal.tp3:.2f}" if signal.tp3 else "N/A"
        zone     = market_data.get("zone_label", "N/A")

        # Learned stats → historical context for AI
        learned: dict = market_data.get("learned_stats", {})
        zone_type = zone.split("_")[-1] if "_" in zone else zone
        hist_lines = []
        for typ, s in sorted(learned.items(), key=lambda x: -x[1]["total"]):
            hist_lines.append(
                f"  {typ}: WR={s['win_rate']*100:.0f}% ({s['total']} trades)"
            )
        hist_block = "\n".join(hist_lines[:8]) if hist_lines else "  No data yet"

        # Session/day weight context
        sd_weight = market_data.get("session_day_weight", 1.0)
        sd_label  = market_data.get("session_day_label", "")
        sd_note   = f"{sd_label} (weight={sd_weight:.2f})" if sd_label else "N/A"

        # DXY note
        dxy_note  = market_data.get("dxy_note", "N/A")

        # W1 bias
        w1_bias   = market_data.get("w1_bias", "N/A")

        d1_trend = market_data.get("d1_trend", "N/A")
        h4_trend = market_data.get("h4_trend", "N/A")
        h1_trend = market_data.get("h1_trend", "N/A")
        zone_tf  = market_data.get("zone_tf", "N/A")

        return f"""XAUUSD ICT TRADE SIGNAL — VALIDATION

Direction : {signal.direction.upper()}
Zone      : {zone}  (from {zone_tf} timeframe)
Entry     : {signal.entry:.2f}
SL        : {signal.sl:.2f}  ({sl_pips} pips)
TP1       : {signal.tp1:.2f}  ({tp1_pips} pips)
TP2       : {tp2_str}
TP3       : {tp3_str}
RR        : 1:{signal.rr_ratio:.2f}
Quality   : {signal.confluence_score:.0f}/20

HTF Bias (use these for alignment check — NOT the zone-TF signal below):
- W1 Bias     : {w1_bias}
- D1 Trend    : {d1_trend}
- H4 Trend    : {h4_trend}   ← PRIMARY HTF CHECK
- H1 Trend    : {h1_trend}

Zone-TF Analysis ({zone_tf} — entry confirmation only, not HTF):
- Signal      : {ict.signal_type if ict else 'N/A'}
- Trend       : {st.get('trend', 'N/A')}
- MMXM phase  : {st.get('mmxm', 'N/A')} ({st.get('mmxm_dir', 'N/A')})
- MMXM swept  : {st.get('mmxm_swept', False)}
- BOS count   : {st.get('bos', 0)}
- CHoCH       : {st.get('choch', False)}
- Judas swing : {st.get('judas', False)}
- Stop hunt   : {st.get('stop_hunt', False)}
- Displacement: {st.get('displacement', False)}
- OB count    : {len(ict.order_blocks) if ict else 0}
- FVG count   : {len(ict.fvgs) if ict else 0}
- PD zone     : {ict.pd_zone if ict else 'N/A'}
- Kill zone   : {ict.kill_zone if ict else 'N/A'}

Market Context:
- Session/Day : {sd_note}
- DXY corr    : {dxy_note}
- Balance     : ${market_data.get('account_balance', 0):.2f}

Historical Performance (this bot, last 50 trades):
{hist_block}
Current setup type: {zone_type}

Reply with JSON only."""
